syntax = "proto3";

package livekit;

message Room {
  string sid = 1;
  string name = 2;
  uint32 empty_timeout = 3;
  uint32 departure_timeout = 14;
  uint32 max_participants = 4;
  int64 creation_time = 5;
  string turn_password = 6;
  repeated Codec enabled_codecs = 7;
  string metadata = 8;
  uint32 num_participants = 9;
  uint32 num_publishers = 11;
  bool active_recording = 10;
  TimedVersion version = 13;
}

message Codec {
  string mime = 1;
  string fmtp_line = 2;
}

message ParticipantPermission {
  bool can_subscribe = 1;
  bool can_publish = 2;
  bool can_publish_data = 3;
  repeated TrackSource can_publish_sources = 9;
  bool hidden = 7;
  bool recorder = 8;
  bool can_update_metadata = 10;
  bool agent = 11;
}

message ParticipantInfo {
  string sid = 1;
  string identity = 2;
  ParticipantInfo.State state = 3;
  repeated TrackInfo tracks = 4;
  string metadata = 5;
  int64 joined_at = 6;
  string name = 9;
  uint32 version = 10;
  ParticipantPermission permission = 11;
  string region = 12;
  bool is_publisher = 13;
  ParticipantInfo.Kind kind = 14;
  map<string, string> attributes = 15;
  int64 disconnected_at = 16;

  enum State {
    JOINING = 0;
    JOINED = 1;
    ACTIVE = 2;
    DISCONNECTED = 3;
  }

  enum Kind {
    STANDARD = 0;
    INGRESS = 1;
    EGRESS = 2;
    SIP = 3;
    AGENT = 4;
  }
}

message TrackInfo {
  string sid = 1;
  TrackType type = 2;
  string name = 3;
  bool muted = 4;
  uint32 width = 5;
  uint32 height = 6;
  bool simulcast = 7;
  bool disable_dtx = 8;
  TrackSource source = 9;
  repeated VideoLayer layers = 10;
  string mime_type = 11;
  string mid = 12;
  repeated Codec codecs = 13;
  bool stereo = 14;
  bool disable_red = 15;
  Encryption.Type encryption = 16;
  string stream = 17;
  TimedVersion version = 18;
  AudioTrackFeature audio_features = 19;
}

message VideoLayer {
  VideoQuality quality = 1;
  uint32 width = 2;
  uint32 height = 3;
  uint32 bitrate = 4;
  uint32 ssrc = 5;
}

message DataPacket {
  DataPacket.Kind kind = 1;
  oneof value {
    UserPacket user = 2;
    ActiveSpeakerUpdate speaker = 3;
    SipDTMF sip_dtmf = 5;
    Transcription transcription = 6;
  }

  enum Kind {
    RELIABLE = 0;
    LOSSY = 1;
  }
}

message ActiveSpeakerUpdate {
  repeated SpeakerInfo speakers = 1;
}

message SpeakerInfo {
  string sid = 1;
  float level = 2;
  bool active = 3;
}

message UserPacket {
  string participant_sid = 1;
  string participant_identity = 5;
  bytes payload = 2;
  repeated string destination_sids = 3;
  repeated string destination_identities = 6;
  optional string topic = 4;
  uint64 id = 7;
  uint64 start_time = 8;
  uint64 end_time = 9;
}

message ParticipantTracks {
  string participant_sid = 1;
  repeated string track_sids = 2;
}

message Transcription {
  string transcribed_participant_identity = 1;
  string track_sid = 2;
  repeated TranscriptionSegment segments = 3;
}

message TranscriptionSegment {
  string id = 1;
  string text = 2;
  uint64 start_time = 3;
  uint64 end_time = 4;
  bool final = 5;
  string language = 6;
}

message SipDTMF {
  uint32 code = 3;
  string digit = 4;
}

message TimedVersion {
  int64 unix_micro = 1;
  int32 ticks = 2;
}

message Encryption {
  enum Type {
    NONE = 0;
    GCM = 1;
    CUSTOM = 2;
  }
}

message AudioTrackFeature {
  bool tts = 1;
}

enum TrackType {
  AUDIO = 0;
  VIDEO = 1;
  DATA = 2;
}

enum TrackSource {
  UNKNOWN = 0;
  CAMERA = 1;
  MICROPHONE = 2;
  SCREEN_SHARE = 3;
  SCREEN_SHARE_AUDIO = 4;
}

enum VideoQuality {
  LOW = 0;
  MEDIUM = 1;
  HIGH = 2;
  OFF = 3;
}
