defmodule Livekitex.RoomServiceTwirpTest do
  use ExUnit.Case, async: true

  # Test the generated Twirp service module
  alias Livekitex.RoomServiceTwirp

  describe "Twirp service module" do
    test "is defined and loadable" do
      # Verify the module exists and can be loaded
      assert Code.ensure_loaded?(RoomServiceTwirp)
    end

    test "uses Twirp.Service" do
      # Verify the module uses the Twirp.Service macro
      # This is indicated by the presence of the @moduledoc false and use Twirp.Service
      # Note: moduledoc might be nil instead of [false] in some versions
      moduledoc = RoomServiceTwirp.__info__(:attributes)[:moduledoc]
      assert moduledoc == [false] or moduledoc == nil
    end

    test "implements Twirp.Service behaviour" do
      # Verify the module properly implements the Twirp.Service behaviour
      # The presence of definition/0 function and proper structure indicates this
      assert function_exported?(RoomServiceTwirp, :definition, 0)
      
      definition = RoomServiceTwirp.definition()
      assert is_map(definition)
      assert Map.has_key?(definition, :package)
      assert Map.has_key?(definition, :service)
      assert Map.has_key?(definition, :rpcs)
    end

    test "has definition function generated by Twirp" do
      # The Twirp.Service macro generates a definition/0 function
      assert function_exported?(RoomServiceTwirp, :definition, 0)
    end

    test "definition returns service configuration" do
      definition = RoomServiceTwirp.definition()
      
      # The definition should be a map with service configuration
      assert is_map(definition)
      assert definition.package == "livekit"
      assert definition.service == "RoomService"
      assert is_list(definition.rpcs)
    end
  end

  describe "service configuration" do
    test "defines correct package name" do
      definition = RoomServiceTwirp.definition()
      assert definition.package == "livekit"
    end

    test "defines correct service name" do
      definition = RoomServiceTwirp.definition()
      assert definition.service == "RoomService"
    end

    test "defines all expected RPC methods" do
      definition = RoomServiceTwirp.definition()
      rpcs = definition.rpcs

      expected_methods = [
        :CreateRoom,
        :ListRooms, 
        :DeleteRoom,
        :ListParticipants,
        :RemoveParticipant,
        :MutePublishedTrack
      ]

      method_names = Enum.map(rpcs, & &1.method)

      for expected_method <- expected_methods do
        assert expected_method in method_names, 
          "Expected method #{expected_method} to be defined"
      end
    end

    test "CreateRoom method configuration" do
      definition = RoomServiceTwirp.definition()
      create_room_method = Enum.find(definition.rpcs, & &1.method == :CreateRoom)

      assert create_room_method != nil
      assert create_room_method.input == Livekit.CreateRoomRequest
      assert create_room_method.output == Livekit.Room
      assert create_room_method.handler_fn == :create_room
    end

    test "ListRooms method configuration" do
      definition = RoomServiceTwirp.definition()
      list_rooms_method = Enum.find(definition.rpcs, & &1.method == :ListRooms)

      assert list_rooms_method != nil
      assert list_rooms_method.input == Livekit.ListRoomsRequest
      assert list_rooms_method.output == Livekit.ListRoomsResponse
      assert list_rooms_method.handler_fn == :list_rooms
    end

    test "DeleteRoom method configuration" do
      definition = RoomServiceTwirp.definition()
      delete_room_method = Enum.find(definition.rpcs, & &1.method == :DeleteRoom)

      assert delete_room_method != nil
      assert delete_room_method.input == Livekit.DeleteRoomRequest
      assert delete_room_method.output == Livekit.DeleteRoomResponse
      assert delete_room_method.handler_fn == :delete_room
    end

    test "ListParticipants method configuration" do
      definition = RoomServiceTwirp.definition()
      list_participants_method = Enum.find(definition.rpcs, & &1.method == :ListParticipants)

      assert list_participants_method != nil
      assert list_participants_method.input == Livekit.ListParticipantsRequest
      assert list_participants_method.output == Livekit.ListParticipantsResponse
      assert list_participants_method.handler_fn == :list_participants
    end

    test "RemoveParticipant method configuration" do
      definition = RoomServiceTwirp.definition()
      remove_participant_method = Enum.find(definition.rpcs, & &1.method == :RemoveParticipant)

      assert remove_participant_method != nil
      assert remove_participant_method.input == Livekit.RoomParticipantIdentity
      assert remove_participant_method.output == Livekit.RemoveParticipantResponse
      assert remove_participant_method.handler_fn == :remove_participant
    end

    test "MutePublishedTrack method configuration" do
      definition = RoomServiceTwirp.definition()
      mute_track_method = Enum.find(definition.rpcs, & &1.method == :MutePublishedTrack)

      assert mute_track_method != nil
      assert mute_track_method.input == Livekit.MuteRoomTrackRequest
      assert mute_track_method.output == Livekit.MuteRoomTrackResponse
      assert mute_track_method.handler_fn == :mute_published_track
    end
  end

  describe "handler functions" do
    test "handler function names are properly configured" do
      # Verify that all the handler functions are properly configured in the RPC definitions
      definition = RoomServiceTwirp.definition()
      
      expected_handlers = [
        :create_room,
        :list_rooms,
        :delete_room,
        :list_participants,
        :remove_participant,
        :mute_published_track
      ]
      
      actual_handlers = Enum.map(definition.rpcs, & &1.handler_fn)
      
      for expected_handler <- expected_handlers do
        assert expected_handler in actual_handlers,
          "Expected handler function #{expected_handler} to be configured"
      end
    end

    test "handler functions are atoms" do
      # Each Twirp handler should be an atom
      definition = RoomServiceTwirp.definition()

      for rpc <- definition.rpcs do
        handler = rpc.handler_fn
        assert is_atom(handler),
          "Handler #{handler} should be an atom"
      end
    end
  end

  describe "protobuf message types" do
    test "all input message types are valid protobuf modules" do
      definition = RoomServiceTwirp.definition()

      for rpc <- definition.rpcs do
        input_type = rpc.input

        # Verify it's a loaded protobuf module
        assert Code.ensure_loaded?(input_type),
          "Input type #{input_type} should be loadable"
        
        # Protobuf modules should have certain functions
        assert function_exported?(input_type, :new, 0) or function_exported?(input_type, :new, 1),
          "#{input_type} should have new/0 or new/1 function"
      end
    end

    test "all output message types are valid protobuf modules" do
      definition = RoomServiceTwirp.definition()

      for rpc <- definition.rpcs do
        output_type = rpc.output

        # Verify it's a loaded protobuf module
        assert Code.ensure_loaded?(output_type),
          "Output type #{output_type} should be loadable"
        
        # Protobuf modules should have certain functions
        assert function_exported?(output_type, :new, 0) or function_exported?(output_type, :new, 1),
          "#{output_type} should have new/0 or new/1 function"
      end
    end
  end

  describe "Twirp endpoints" do
    test "can generate endpoint paths" do
      definition = RoomServiceTwirp.definition()
      
      # Each method should correspond to a Twirp endpoint path
      for rpc <- definition.rpcs do
        expected_path = "/twirp/#{definition.package}.#{definition.service}/#{rpc.method}"
        
        # We can't directly test the endpoint generation without the Twirp server,
        # but we can verify the structure is correct for generating paths
        assert is_binary(definition.package)
        assert is_binary(definition.service)
        assert is_atom(rpc.method)
        assert String.starts_with?(expected_path, "/twirp/")
      end
    end

    test "method names follow Twirp conventions" do
      definition = RoomServiceTwirp.definition()

      for rpc <- definition.rpcs do
        method_name = Atom.to_string(rpc.method)
        
        # Twirp method names should be PascalCase when converted to string
        assert String.match?(method_name, ~r/^[A-Z][A-Za-z0-9]*$/),
          "Method name '#{method_name}' should be in PascalCase"
      end
    end
  end

  describe "service integration" do
    test "package name follows protobuf conventions" do
      definition = RoomServiceTwirp.definition()
      package = definition.package
      
      # Package names should be lowercase and may contain dots
      assert String.match?(package, ~r/^[a-z][a-z0-9]*(?:\.[a-z][a-z0-9]*)*$/),
        "Package name '#{package}' should follow protobuf naming conventions"
    end

    test "service name follows protobuf conventions" do
      definition = RoomServiceTwirp.definition()
      service = definition.service
      
      # Service names should start with uppercase letter
      assert String.match?(service, ~r/^[A-Z][A-Za-z0-9]*$/),
        "Service name '#{service}' should follow protobuf naming conventions"
    end

    test "service has complete method definitions" do
      definition = RoomServiceTwirp.definition()
      
      # Verify each method has complete configuration
      for rpc <- definition.rpcs do
        assert is_atom(rpc.method)
        assert is_atom(rpc.input) 
        assert is_atom(rpc.output)
        assert is_atom(rpc.handler_fn)
        
        # Verify the configuration is not nil
        refute is_nil(rpc.method)
        refute is_nil(rpc.input)
        refute is_nil(rpc.output)
        refute is_nil(rpc.handler_fn)
      end
    end

    test "service configuration is consistent" do
      definition = RoomServiceTwirp.definition()
      
      # Basic consistency checks
      assert length(definition.rpcs) == 6, "Expected 6 RPC methods"
      assert definition.package != ""
      assert definition.service != ""
      
      # All methods should have unique names
      method_names = Enum.map(definition.rpcs, & &1.method)
      assert length(method_names) == length(Enum.uniq(method_names)),
        "All method names should be unique"
    end
  end
end